"use client";
import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight } from "lucide-react";
import { useWallet, walletMessage } from "./wallet";

const brands = [
  { name: "Stripe", style: { fontFamily: "Georgia, serif", fontWeight: 700, letterSpacing: "-0.02em", fontSize: "15px" } },
  { name: "Coinbase", style: { fontFamily: "Arial, sans-serif", fontWeight: 900, letterSpacing: "0.08em", fontSize: "13px", textTransform: "uppercase" } },
  { name: "Uniswap", style: { fontFamily: '"Trebuchet MS", sans-serif', fontWeight: 600, letterSpacing: "0.01em", fontSize: "15px", fontStyle: "italic" } },
  { name: "Aave", style: { fontFamily: '"Courier New", monospace', fontWeight: 700, letterSpacing: "0.12em", fontSize: "13px", textTransform: "uppercase" } },
  { name: "Compound", style: { fontFamily: '"Palatino Linotype", "Book Antiqua", Palatino, serif', fontWeight: 400, letterSpacing: "-0.01em", fontSize: "16px" } },
  { name: "MakerDAO", style: { fontFamily: 'Impact, "Arial Narrow", sans-serif', fontWeight: 400, letterSpacing: "0.04em", fontSize: "14px" } },
  { name: "Chainlink", style: { fontFamily: "Verdana, sans-serif", fontWeight: 700, letterSpacing: "-0.03em", fontSize: "13px" } },
];

const backers = [
  { name: "Fundamental Labs", style: { fontFamily: '"Times New Roman", Times, serif', fontWeight: 400, letterSpacing: "0.02em", fontSize: "14px" } },
  { name: "KUCOIN", style: { fontFamily: '"Arial Black", Gadget, sans-serif', fontWeight: 900, letterSpacing: "0.08em", fontSize: "16px" } },
  { name: "NGC", style: { fontFamily: "Impact, Charcoal, sans-serif", fontWeight: 700, letterSpacing: "0.05em", fontSize: "18px" } },
  { name: "NxGen", style: { fontFamily: "Georgia, serif", fontWeight: 600, letterSpacing: "-0.02em", fontSize: "17px" } },
  { name: "Matter Labs", style: { fontFamily: "Helvetica, Arial, sans-serif", fontWeight: 700, letterSpacing: "-0.01em", fontSize: "15px" } },
  { name: "DEXTools", style: { fontFamily: "Verdana, Geneva, sans-serif", fontWeight: 700, letterSpacing: "0.06em", fontSize: "14px", textTransform: "uppercase" } },
  { name: "NGRAVE", style: { fontFamily: '"Courier New", Courier, monospace', fontWeight: 700, letterSpacing: "0.18em", fontSize: "14px" } },
  { name: "Polychain", style: { fontFamily: '"Palatino Linotype", "Book Antiqua", Palatino, serif', fontWeight: 500, letterSpacing: "0.03em", fontSize: "15px" } },
];

/**
 * Each use case maps to a profile the product can actually issue, so the tab
 * is not decorative — it is the entry point to that flow.
 */
const useCaseDetails = {
  commerce: {
    title: "Commerce",
    profile: "freelancer",
    description:
      "Lift customer retention by offering PersonaOS, a trusted Stellar-anchored identity layer that allows patrons to prove creditworthiness with zero raw data exposure.",
  },
  lending: {
    title: "Lending",
    profile: "loan",
    description:
      "Apply for credit or loans using a verified income stability, debt ratio, and repayment discipline proof generated by your Twin without ever uploading raw statements.",
  },
  hiring: {
    title: "Hiring",
    profile: "hiring",
    description:
      "Verify your income stability, work history, and repository contributions instantly while keeping your specific salary details and document copies strictly confidential.",
  },
  rental: {
    title: "Rental",
    profile: "insurance",
    description:
      "Prove rent payment consistency, identity verification, and employment stability to landlords with a secure, cryptographically signed attestation.",
  },
};

const short = (a) => `${a.slice(0, 4)}…${a.slice(-4)}`;

export default function Landing() {
  const [activeUseCase, setActiveUseCase] = useState("commerce");
  const { address, connect, connecting, errorCode } = useWallet();
  const active = useCaseDetails[activeUseCase];
  const problem = errorCode ? walletMessage(errorCode) : null;

  return (
    <div className="flex flex-col bg-[#F5F5F5] min-h-screen">
      {/* NAVBAR + HERO */}
      <div className="h-screen flex flex-col overflow-hidden relative container max-w-[88rem] mx-auto w-full px-6">
        <nav className="absolute top-0 left-0 right-0 z-20 px-6 py-5">
          <div className="flex items-center justify-between max-w-[88rem] mx-auto">
            <div className="flex items-center gap-4">
              <Image src="/Logo.png" alt="" width={40} height={40} className="h-10 w-auto object-contain" priority />
              <span className="text-2xl font-semibold tracking-tight text-black font-barlow">PersonaOS</span>
            </div>

            <div className="hidden md:flex items-center gap-8">
              <a href="#memory" className="text-sm tracking-wider uppercase font-semibold text-gray-700 hover:text-black font-barlow transition-colors duration-200">Memory</a>
              <a href="#modes" className="text-sm tracking-wider uppercase font-semibold text-gray-700 hover:text-black font-barlow transition-colors duration-200">Modes</a>
              <Link href="/vault" className="text-sm tracking-wider uppercase font-semibold text-gray-700 hover:text-black font-barlow transition-colors duration-200">Vault</Link>
              <Link href="/verify" className="text-sm tracking-wider uppercase font-semibold text-gray-700 hover:text-black font-barlow transition-colors duration-200">Verify</Link>
            </div>

            {address ? (
              <Link
                href="/vault"
                className="bg-[#2b2644] text-white text-sm tracking-wider uppercase font-semibold px-8 py-3 rounded-full hover:bg-[#3a3358] font-barlow transition-colors duration-200"
              >
                {short(address)}
              </Link>
            ) : (
              <button
                onClick={connect}
                disabled={connecting}
                className="bg-black text-white text-sm tracking-wider uppercase font-semibold px-8 py-3 rounded-full hover:bg-gray-800 font-barlow transition-colors duration-200 cursor-pointer disabled:opacity-50"
              >
                {connecting ? "Connecting…" : "Connect Twin"}
              </button>
            )}
          </div>

          {/* Connection failed — say what happened and offer the way out. */}
          {problem && (
            <div className="max-w-[88rem] mx-auto mt-4 flex justify-end">
              <div className="rise bg-white border border-black/8 rounded-2xl shadow-sm p-6 max-w-sm">
                <p className="font-barlow text-[10px] font-semibold uppercase tracking-[0.2em] text-[#b4483c] mb-2">
                  Can&rsquo;t connect
                </p>
                <p className="font-serif text-xl text-black mb-2" style={{ letterSpacing: "-0.02em" }}>
                  {problem.title}
                </p>
                <p className="font-sans font-light text-sm text-black/60 leading-relaxed mb-5">
                  {problem.body}
                </p>
                <div className="flex flex-wrap gap-2.5">
                  {problem.action && (
                    <a
                      href={problem.action.href}
                      target="_blank"
                      rel="noreferrer"
                      className="font-barlow text-[11px] font-semibold uppercase tracking-[0.1em] bg-black text-white px-5 py-2 rounded-full hover:bg-gray-800 transition-colors"
                    >
                      {problem.action.label}
                    </a>
                  )}
                  <button
                    onClick={connect}
                    disabled={connecting}
                    className="font-barlow text-[11px] font-semibold uppercase tracking-[0.1em] border border-black/15 px-5 py-2 rounded-full hover:border-black/40 transition-colors cursor-pointer disabled:opacity-50"
                  >
                    {connecting ? "Connecting" : problem.retry}
                  </button>
                </div>
              </div>
            </div>
          )}
        </nav>

        <div className="flex-1 pt-20 pb-6 flex items-end relative w-full">
          <div className="relative w-full rounded-2xl overflow-hidden bg-black/5" style={{ height: "calc(100vh - 96px)" }}>
            <video
              className="object-cover absolute inset-0 w-full h-full"
              autoPlay
              muted
              loop
              playsInline
              src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260423_161253_c72b1869-400f-45ed-ac0c-52f68c2ed5bd.mp4"
            />

            <div className="relative z-10 flex flex-col items-start justify-start h-full p-12 pt-36">
              <h1
                className="text-black text-5xl md:text-6xl font-serif font-normal leading-tight max-w-xl mb-4"
                style={{ letterSpacing: "-0.04em" }}
              >
                Your <span className="italic font-light text-black/85">Memory</span>
                <br />
                Works
              </h1>
              <p className="text-black/70 text-base md:text-lg max-w-md mb-8 leading-relaxed font-sans font-light">
                A continuously learning, AI-native economic identity layer built for programmable finance and
                privacy-preserving proofs.
              </p>
              <Link
                href="/vault"
                className="inline-flex items-center gap-3 bg-black text-white text-base md:text-lg font-medium pl-8 pr-2 py-2 rounded-full hover:bg-gray-800 font-barlow transition-colors duration-200 group cursor-pointer"
              >
                <span>Launch Twin</span>
                <span className="bg-white rounded-full p-2 group-hover:bg-gray-100 transition-colors duration-200">
                  <ArrowRight className="w-5 h-5 text-black" />
                </span>
              </Link>

              <div className="mt-24 w-full max-w-md overflow-hidden relative">
                <div className="marquee-track">
                  {[...brands, ...brands].map((item, idx) => (
                    <span key={idx} className="mx-7 shrink-0 text-black/60 whitespace-nowrap" style={item.style}>
                      {item.name}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* MEET PERSONAOS */}
      <section id="memory" className="bg-[#F5F5F5] px-6 py-24 w-full scroll-mt-8">
        <div className="max-w-[88rem] mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 mb-16 items-start">
            <div>
              <h2
                className="text-black text-5xl md:text-7xl font-serif font-normal leading-tight mb-8"
                style={{ letterSpacing: "-0.03em" }}
              >
                Meet PersonaOS.
              </h2>
              <Link
                href="/vault"
                className="inline-flex items-center gap-3 bg-black text-white text-sm font-semibold tracking-wider uppercase pl-8 pr-2 py-2 rounded-full hover:bg-gray-800 font-barlow transition-colors duration-200 group cursor-pointer"
              >
                <span>Build your memory</span>
                <span className="bg-white rounded-full p-2 group-hover:bg-gray-100 transition-colors duration-200">
                  <ArrowRight className="w-4 h-4 text-black" />
                </span>
              </Link>
            </div>
            <div>
              <p className="text-black/80 text-2xl md:text-3xl leading-relaxed font-sans font-light">
                PersonaOS is an economic memory layer that translates raw, fragmented financial histories into
                semantic meaning, allowing you to share context-specific proofs without exposing private raw data.
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div
              className="lg:col-span-2 rounded-2xl p-7 min-h-80 flex flex-col justify-between"
              style={{
                backgroundImage:
                  "url('https://images.higgs.ai/?default=1&output=webp&url=https%3A%2F%2Fd8j0ntlcm91z4.cloudfront.net%2Fuser_38xzZboKViGWJOttwIXH07lWA1P%2Fhf_20260423_164207_f243351d-ed59-48ec-83a0-a5e996bdbe3c.png&w=1280&q=85')",
                backgroundSize: "cover",
                backgroundPosition: "center",
              }}
            >
              <h3 className="text-black text-3xl font-serif font-normal leading-snug" style={{ letterSpacing: "-0.02em" }}>
                Memory that blooms
              </h3>
              <p className="text-black/70 text-base max-w-xs leading-relaxed font-sans font-light">
                Gain deep semantic returns as your financial activities are processed by your private, local-first AI Twin.
              </p>
            </div>

            <div className="bg-[#2B2644] rounded-2xl p-7 min-h-80 flex flex-col justify-between text-white">
              <h3 className="text-3xl font-serif font-normal leading-tight">
                Always private,
                <br />
                always verified.
              </h3>
              <p className="text-white/70 text-base leading-relaxed font-sans font-light">
                Keep full data ownership. Share cryptographically verifiable proofs anchored on Stellar without exposing
                raw documents.
              </p>
            </div>

            <div className="bg-[#2B2644] rounded-2xl p-7 min-h-80 flex flex-col justify-between text-white">
              <h3 className="text-3xl font-serif font-normal leading-tight">
                Fully
                <br />
                automated.
              </h3>
              <p className="text-white/70 text-base leading-relaxed font-sans font-light">
                Skip compiling bank statements or work history. Your Persona Twin works continuously in the background
                for you.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* BACKED BY */}
      { /* <section className="bg-[#F5F5F5] px-6 py-16 border-t border-b border-black/5 w-full">
        <div className="max-w-[88rem] mx-auto grid grid-cols-1 md:grid-cols-4 gap-8 items-center">
          <div className="text-black/70 text-base leading-relaxed font-sans font-light">
            Funded by premier partners
            <br />
            and forward-thinking leaders.
          </div>
          <div className="md:col-span-3 overflow-hidden relative w-full">
            <div className="backers-track">
              {[...backers, ...backers].map((item, idx) => (
                <span key={idx} className="mx-10 shrink-0 text-black/50 whitespace-nowrap" style={item.style}>
                  {item.name}
                </span>
              ))}
            </div>
          </div>
        </div>
      </section>
*/}

      {/* USE MODES — each tab now opens the profile it describes */}
      <section id="modes" className="bg-[#F5F5F5] px-6 py-24 w-full scroll-mt-8">
        <div className="max-w-[88rem] mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 items-start">
          <div className="md:pr-12 md:pt-2">
            <p className="text-black/60 text-sm font-semibold tracking-wider uppercase font-barlow mb-2">
              PersonaOS in Practice
            </p>
            <h2
              className="text-black text-5xl md:text-7xl font-serif font-normal leading-none mb-6"
              style={{ letterSpacing: "-0.04em" }}
            >
              Use modes
            </h2>
            <p className="text-black/60 text-base leading-relaxed max-w-sm font-sans font-light mb-8">
              PersonaOS powers a wide range of modes for builders, companies and treasuries wanting safe and rewarding
              stablecoin integrations plus more.
            </p>

            <div className="mt-8 flex flex-col gap-3 max-w-xs">
              {Object.keys(useCaseDetails).map((mode) => (
                <button
                  key={mode}
                  onClick={() => setActiveUseCase(mode)}
                  aria-pressed={activeUseCase === mode}
                  className={`w-full text-left px-5 py-4 rounded-xl border transition-all duration-200 flex items-center justify-between cursor-pointer font-barlow ${activeUseCase === mode
                      ? "bg-black text-white border-black shadow-sm font-semibold"
                      : "bg-white/50 text-gray-700 border-black/10 hover:border-black/30 hover:bg-white"
                    }`}
                >
                  <span className="capitalize">{mode}</span>
                  <ArrowRight
                    className={`w-4 h-4 transition-transform duration-200 ${activeUseCase === mode ? "translate-x-1 text-white" : "text-gray-400"
                      }`}
                  />
                </button>
              ))}
            </div>
          </div>

          <div className="relative rounded-3xl overflow-hidden min-h-[720px] shadow-sm flex flex-col justify-start">
            <video
              className="absolute inset-0 w-full h-full object-cover"
              autoPlay
              muted
              loop
              playsInline
              src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260423_183428_ab5e672a-f608-4dcb-b319-f3e040f02e2d.mp4"
            />

            <div className="relative z-10 p-10 md:p-12">
              <h3
                className="text-black text-4xl md:text-5xl font-serif font-normal leading-tight mb-5"
                style={{ letterSpacing: "-0.03em" }}
              >
                {active.title}
              </h3>
              <p className="text-black/70 text-base leading-relaxed max-w-md mb-8 font-sans font-light">
                {active.description}
              </p>

              <Link
                href={`/issue?type=${active.profile}`}
                className="inline-flex items-center gap-3 text-black text-base font-semibold font-barlow group cursor-pointer"
              >
                <span className="w-9 h-9 rounded-full bg-white/80 backdrop-blur flex items-center justify-center group-hover:bg-white transition-colors duration-200">
                  <ArrowRight className="w-4 h-4 text-black" />
                </span>
                Issue this proof
              </Link>
            </div>
          </div>
        </div>
      </section>

      <footer className="bg-[#F5F5F5] py-12 px-6 border-t border-black/5 w-full">
        <div className="max-w-[88rem] mx-auto flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            <Image src="/Logo.png" alt="" width={32} height={32} className="h-8 w-auto opacity-40 object-contain" />
            <span className="text-base font-semibold tracking-tight text-black/40 font-barlow">
              PersonaOS © {new Date().getFullYear()}
            </span>
          </div>
          <div className="flex gap-8 text-sm text-black/40 font-barlow font-medium">
            <Link href="/vault" className="hover:text-black transition-colors">Vault</Link>
            <Link href="/issue" className="hover:text-black transition-colors">Issue</Link>
            <Link href="/verify" className="hover:text-black transition-colors">Verify</Link>
            <a
              href="https://github.com/vardanagarwal11/PersonaOS"
              target="_blank"
              rel="noreferrer"
              className="hover:text-black transition-colors"
            >
              GitHub
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
